apiVersion: apps/v1
kind: Deployment
metadata:
  name: Web-liveness-readiness-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      run: web-demo
  template:
    metadata:
      labels:
        run: web-demo
    spec:
      containers:
      - image: nginx:1.23.1
        name: web-demo
        env:
        - name: START_DELAY
          value: "0"        
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1  
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
