apiVersion: v1
kind: Service
metadata:
  name: web-demo
spec:
  selector:
    run: web-demo
  type: NodePort
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001